// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSXDlb74A_qSydGw9EuYX-Ai8gRzK5zdg',
    appId: '1:659070244201:web:8724fba3a97132da9459f8',
    messagingSenderId: '659070244201',
    projectId: 'dhavla-2024',
    authDomain: 'dhavla-2024.firebaseapp.com',
    storageBucket: 'dhavla-2024.appspot.com',
    measurementId: 'G-KT7BMRDJ5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPCuISZRpABF0vgSwI1L02A-wa1WVVeyo',
    appId: '1:659070244201:android:22f8768b99c86b2e9459f8',
    messagingSenderId: '659070244201',
    projectId: 'dhavla-2024',
    storageBucket: 'dhavla-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzqKvyhyhfcuHz8uOdmGn_jjQIPLenJio',
    appId: '1:659070244201:ios:653f4d5948e190df9459f8',
    messagingSenderId: '659070244201',
    projectId: 'dhavla-2024',
    storageBucket: 'dhavla-2024.appspot.com',
    iosBundleId: 'com.example.dhavlaRoadProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzqKvyhyhfcuHz8uOdmGn_jjQIPLenJio',
    appId: '1:659070244201:ios:653f4d5948e190df9459f8',
    messagingSenderId: '659070244201',
    projectId: 'dhavla-2024',
    storageBucket: 'dhavla-2024.appspot.com',
    iosBundleId: 'com.example.dhavlaRoadProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSXDlb74A_qSydGw9EuYX-Ai8gRzK5zdg',
    appId: '1:659070244201:web:3c63e1d35d51b1c19459f8',
    messagingSenderId: '659070244201',
    projectId: 'dhavla-2024',
    authDomain: 'dhavla-2024.firebaseapp.com',
    storageBucket: 'dhavla-2024.appspot.com',
    measurementId: 'G-LVFSDFDE0L',
  );
}
